# spring.application.name=location-service
# server.port=8083

# spring.data.redis.host=localhost
# spring.data.redis.port=6379

# jwt.secret=miniuber-super-secret-key-change-this-in-production-2024
# jwt.expiration=86400000

spring.application.name=location-service
server.port=8083
spring.data.redis.host=redis
spring.data.redis.port=6379
jwt.secret=miniuber-super-secret-key-change-this-in-production-2024
jwt.expiration=86400000